### PR TITLE
Remove bower

### PR DESCRIPTION
**Pull request by nicolasdanelon**

### CODE REVIEW

**Comment by nicolasdanelon** [comment]
Since bower is dead.. I upgrade the theme to yarn and remove everything that "we don't need".
_npm all the things_
if you like my work please let me know. I have to update the readme file yet.. But I want to know your impression about this PR

**Comment by nicolasdanelon** [comment]
BTW: I don't know what to do about the last commit :P

**Comment by kalvn** [comment]
Thanks @nicolasdanelon, that needed to be done!

I'll review all that and test it locally but it looks great :)

**Comment by kalvn** [comment]
I tried to install dependencies with Yarn and got this error. Does it look familiar to you?
image

**Comment by nicolasdanelon** [comment]
not at all... but I'm pretty sure I don't have PhantomJS in my path

**Comment by kalvn** [comment]
I finally had to do it a bit differently so I didn't use your pull request. Sorry for that. But your work clearly made it a lot easier, thanks! The reorganization will be part of v0.10.3.

**Pull request closed without merging**
