### PR TITLE
Adds Keyboard Shortcuts

### PR DESCRIPTION
**Pull request by Kovah**
Adds keyboard shortcuts to quickly switch to other pages without having to click buttons.

* `Ctrl + H` = Jump to Homepage
* `Ctrl + N` = Create new Bookmark
* `Ctrl + T` = Jump to the Tags overview
* `Ctrl + P` = Jump to the Picwall
* `Ctrl + D` = Jump to the Daily page
* `Ctrl + C` = Jump to the Configration overview

### CODE REVIEW

**Comment by Kovah** [comment]
Whoops, already includes fixes from #59

**Comment by kalvn** [comment]
Adding shortcuts is a good idea. However, I'm not sure that it should be part of this theme since not everyone will use them. And it could cause conflicts with browser's shortcuts. For example, CTRL+C is already widely use to copy text.

Wouldn't it be more relevant as a plugin? Either part of the Shaarli project or external.

**Comment by Kovah** [comment]
CTRL+C is for copying text on Windows devices, isn't it? Darn, didn't remembered that. Usually developing on my mac where CTRL can be taken for most shortcuts.
Will investigate and add it as a plugin if it's working. Thanks for taking a look at it.

**Comment by kalvn** [comment]
Yes, most of CTRL+<key> combinations are most likely already used in Windows.

To cover as mush OS as possible, it might be required to use a more exotic combination such as CTRL+ALT+<key> or something similar.

**Comment by ArthurHoaro** [comment]
Most CTRL combinations are actually mapped by the browser (CTRL+T new tab, CTRL+N new window, etc). As a KDE user, I've also a few custom CTRL+ALT combinations, mainly for window and desktop manipulation. I think it would be a better idea to use either MAJ+`letter` or just `letter`.

Good plugin idea though.

**Pull request closed without merging**
